const { ListOrders } = require('../../src')

const testFunction = async () => {
  const params = { per_page: 2 }
  const res = await ListOrders(params)
  console.log(JSON.stringify(res))
}

testFunction()

// Result

const result = [
  {
    id: 59397,
    parent_id: 0,
    status: 'processing',
    currency: 'MYR',
    version: '4.9.0',
    prices_include_tax: false,
    date_created: '2022-09-15T13:44:21',
    date_modified: '2022-09-15T13:44:22',
    discount_total: '0.00',
    discount_tax: '0.00',
    shipping_total: '10.00',
    shipping_tax: '0.00',
    cart_tax: '0.00',
    total: '59.08',
    total_tax: '0.00',
    customer_id: 0,
    order_key: 'wc_order_Fcx4Ev8aeuCuI',
    billing: {
      first_name: 'Hopstack',
      last_name: 'Dev',
      company: '',
      address_1: '969 Market',
      address_2: '',
      city: 'San Francisco',
      state: 'CA',
      postcode: '94103',
      country: 'US',
      email: 'john.doe@example.com',
      phone: '(555) 555-5555',
    },
    shipping: {
      first_name: 'Hopstack',
      last_name: 'Dev',
      company: '',
      address_1: '969 Market',
      address_2: '',
      city: 'San Francisco',
      state: 'CA',
      postcode: '94103',
      country: 'US',
    },
    payment_method: 'bacs',
    payment_method_title: 'Direct Bank Transfer',
    transaction_id: '',
    customer_ip_address: '',
    customer_user_agent: '',
    created_via: 'rest-api',
    customer_note: '',
    date_completed: null,
    date_paid: '2022-09-15T13:44:22',
    cart_hash: '',
    number: '59397',
    meta_data: [
      { id: 1769385, key: 'wcb2bsa_sales_agent', value: '0' },
      { id: 1769386, key: 'wcb2bsa_order_item_types_eligible_for_commission', value: { line_item: '1' } },
      { id: 1769387, key: 'wcb2bsa_created_by', value: 'customer' },
    ],
    line_items: [
      {
        id: 94259,
        name: 'Test-Product',
        product_id: 59396,
        variation_id: 0,
        quantity: 2,
        tax_class: '',
        subtotal: '49.08',
        subtotal_tax: '0.00',
        total: '49.08',
        total_tax: '0.00',
        taxes: [],
        meta_data: [
          {
            id: 852084,
            key: 'wcb2bsa_item_commission',
            value: '',
            display_key: 'wcb2bsa_item_commission',
            display_value: '',
          },
        ],
        sku: '',
        price: 24.54,
        parent_name: null,
      },
    ],
    tax_lines: [],
    shipping_lines: [
      {
        id: 94260,
        method_title: 'Flat Rate',
        method_id: 'flat_rate',
        instance_id: '',
        total: '10.00',
        total_tax: '0.00',
        taxes: [],
        meta_data: [
          {
            id: 852090,
            key: 'wcb2bsa_item_commission',
            value: '',
            display_key: 'wcb2bsa_item_commission',
            display_value: '',
          },
        ],
      },
    ],
    fee_lines: [],
    coupon_lines: [],
    refunds: [],
    date_created_gmt: '2022-09-15T05:44:21',
    date_modified_gmt: '2022-09-15T05:44:22',
    date_completed_gmt: null,
    date_paid_gmt: '2022-09-15T05:44:22',
    currency_symbol: 'RM',
    wcb2bsa_sales_agent: 0,
    wcb2bsa_order_item_types_eligible_for_commission: { line_item: '1' },
    wcb2bsa_created_by: 'customer',
    _links: {
      self: [{ href: 'https://desamurnibatik.my/wp-json/wc/v3/orders/59397' }],
      collection: [{ href: 'https://desamurnibatik.my/wp-json/wc/v3/orders' }],
    },
  },
  {
    id: 59394,
    parent_id: 0,
    status: 'pending',
    currency: 'MYR',
    version: '4.9.0',
    prices_include_tax: false,
    date_created: '2022-09-15T12:48:50',
    date_modified: '2022-09-15T12:52:26',
    discount_total: '26.00',
    discount_tax: '0.00',
    shipping_total: '10.00',
    shipping_tax: '0.00',
    cart_tax: '0.00',
    total: '170.00',
    total_tax: '0.00',
    customer_id: 0,
    order_key: 'wc_order_gttd5kc1u07d8',
    billing: {
      first_name: 'zurainiza',
      last_name: '',
      company: '',
      address_1: 'no 4 kg bersia lama',
      address_2: '',
      city: 'gerik',
      state: 'PRK',
      postcode: '33320',
      country: 'MY',
      email: '',
      phone: '0186607301',
    },
    shipping: {
      first_name: 'zurainiza',
      last_name: '',
      company: '',
      address_1: 'no 4 kg bersia lama',
      address_2: '',
      city: 'gerik',
      state: 'PRK',
      postcode: '33320',
      country: 'MY',
    },
    payment_method: 'other',
    payment_method_title: 'other',
    transaction_id: '',
    customer_ip_address: '',
    customer_user_agent: '',
    created_via: 'admin',
    customer_note: '',
    date_completed: null,
    date_paid: null,
    cart_hash: '',
    number: '59394',
    meta_data: [
      { id: 1769311, key: 'wcb2bsa_sales_agent', value: '18347' },
      { id: 1769312, key: 'wcb2bsa_order_item_types_eligible_for_commission', value: { line_item: '1' } },
      { id: 1769313, key: 'wcb2bsa_created_by', value: 'sales_agent' },
      { id: 1769331, key: 'slide_template', value: '' },
      { id: 1769332, key: 'rs_page_bg_color', value: '' },
      { id: 1769333, key: 'receipt_uplaoded_attachment_id', value: '59395' },
      { id: 1769334, key: 'receipt_upload_date_uploaded', value: '' },
      { id: 1769335, key: 'receipt_upload_admin_note', value: '' },
    ],
    line_items: [
      {
        id: 94256,
        name: 'Alana - 012/D9/4# Dusty Salmon - 3XL',
        product_id: 46724,
        variation_id: 46727,
        quantity: 1,
        tax_class: '',
        subtotal: '93.00',
        subtotal_tax: '0.00',
        total: '80.00',
        total_tax: '0.00',
        taxes: [],
        meta_data: [
          { id: 852056, key: 'pa_sizes', value: '3xl', display_key: 'sizes', display_value: '3XL' },
          {
            id: 852057,
            key: 'wcb2bsa_item_commission',
            value: '0',
            display_key: 'wcb2bsa_item_commission',
            display_value: '0',
          },
        ],
        sku: '',
        price: 80,
        parent_name: 'Alana - 012/D9/4# Dusty Salmon',
      },
      {
        id: 94257,
        name: 'Alana - 012/D8/5# Teal Blue - 3XL',
        product_id: 46688,
        variation_id: 46691,
        quantity: 1,
        tax_class: '',
        subtotal: '93.00',
        subtotal_tax: '0.00',
        total: '80.00',
        total_tax: '0.00',
        taxes: [],
        meta_data: [
          { id: 852067, key: 'pa_sizes', value: '3xl', display_key: 'sizes', display_value: '3XL' },
          {
            id: 852068,
            key: 'wcb2bsa_item_commission',
            value: '0',
            display_key: 'wcb2bsa_item_commission',
            display_value: '0',
          },
        ],
        sku: '',
        price: 80,
        parent_name: 'Alana - 012/D8/5# Teal Blue',
      },
    ],
    tax_lines: [],
    shipping_lines: [
      {
        id: 94258,
        method_title: 'Shipping',
        method_id: '',
        instance_id: '0',
        total: '10.00',
        total_tax: '0.00',
        taxes: [],
        meta_data: [
          {
            id: 852074,
            key: 'wcb2bsa_item_commission',
            value: '',
            display_key: 'wcb2bsa_item_commission',
            display_value: '',
          },
        ],
      },
    ],
    fee_lines: [],
    coupon_lines: [],
    refunds: [],
    date_created_gmt: '2022-09-15T04:48:50',
    date_modified_gmt: '2022-09-15T04:52:26',
    date_completed_gmt: null,
    date_paid_gmt: null,
    currency_symbol: 'RM',
    wcb2bsa_sales_agent: 18347,
    wcb2bsa_order_item_types_eligible_for_commission: { line_item: '1' },
    wcb2bsa_created_by: 'sales_agent',
    _links: {
      self: [{ href: 'https://desamurnibatik.my/wp-json/wc/v3/orders/59394' }],
      collection: [{ href: 'https://desamurnibatik.my/wp-json/wc/v3/orders' }],
    },
  },
]
